apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  resources:
    - name: source-repo
      type: git

    - name: built-image
      type: image

  params:
    - name: p-pathToDockerFile
      description: path to docker file

    - name: p-pathToContext
      description: path to context

    - name: p-yamlFile
      description: The yaml file to update

    - name: p-yamlImagePath
      description: A tree path for "image" attribute in yaml file

    - name: p-yamls
      description: The yaml(s) to apply

  tasks:
    - name: unit-test-task
      taskRef:
        name: unit-test-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

    - name: lint-task
      taskRef:
        name: lint-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

    - name: acceptance-task
      runAfter: ['lint-task', 'unit-test-task']
      taskRef:
        name: acceptance-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

    - name: e2e-task
      runAfter: ['lint-task', 'unit-test-task']
      taskRef:
        name: e2e-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

    - name: build-task
      runAfter: ['e2e-task', 'acceptance-task']
      taskRef:
        name: build-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

        outputs:
          - name: destImage
            resource: built-image

      params:
        - name: pathToDockerFile
          value: $(params.p-pathToDockerFile)

        - name: pathToContext
          value: $(params.p-pathToContext)

    - name: deploy-task
      runAfter: [build-task]
      taskRef:
        name: deploy-task

      resources:
        inputs:
          - name: source-repo
            resource: source-repo

          - name: new-image
            resource: built-image
            from:
              - build-task

      params:
        - name: yamlFile
          value: $(params.p-yamlFile)

        - name: yamlImagePath
          value: $(params.p-yamlImagePath)

        - name: yamls
          value: $(params.p-yamls)

