apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name:  build-task
spec:
  inputs:
    resources:
      - name: source-repo
        type: git

    params:
      - name: pathToContext
        description: The build context used by Kaniko
        default: .

      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: Dockerfile

  outputs:
    resources:
      - name: destImage
        type: image

  steps:
    - name: build-and-push
      workingdir: /workspace/source
      image: gcr.io/kaniko-project/executor:v0.13.0
      command:
        - /kaniko/executor
      args:
        - --context=/workspace/source-repo/$(inputs.params.pathToContext)
        - --dockerfile=/workspace/source-repo/$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.destImage.url)
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}